name: Fetch daily stats for DD nodes
on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch: {}

jobs:
  update-dd-nodelist:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_CI_TOKEN }}
      - name: Update node count list
        id: fetch
        run: |
          python3 scripts/fetch_daily_dd.py
      - name: Commit changes
        if: steps.fetch.conclusion == 'success'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Daily update
